spring:
  application:
    name: cloud-payment-service #设置注册到EurekaServer注册中心使用的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置eureka相关信息
eureka:
  client:
    #是否在注册中心注册自己
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true
    #如果是单节点无所谓，但是集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #设置与EurekaServer交互的地址，查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://localhost:7007/eureka #单机eureka版
       defaultZone: http://test.dzsc.tk:7007/eureka/,http://test.dzsc.cf:7008/eureka/ #集群eureka版
  instance:
    instance-id: payment8002 #设置服务名称
    prefer-ip-address: true #访问路径显示ip地址

#配置mybatis配置
mybatis:
  type-aliases-package: top.year21.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    #开启在mybatis处理过程中打印出对应的sql语句功能
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启数据库字段自动转换为驼峰命名
    map-underscore-to-camel-case: true

#配置端口号
server:
  port: 8002

