server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route # 路由的ID，没有固定规则但要求必须唯一，建议配置服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的动态路由地址
#          filters:
#            - AddRequestParmter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/query/** #断言，路径相匹配的进行路由
#            - After=2022-08-09T16:46:43.909+08:00[Asia/Shanghai] #断言，必须在这个时间之后才会返回true
#            - Before=2022-08-09T16:46:43.909+08:00[Asia/Shanghai] #断言，必须在这个时间之前才会返回true
#            - Between=2022-08-09T16:46:43.909+08:00[Asia/Shanghai],2022-08-09T17:46:43.909+08:00[Asia/Shanghai] #断言，必须在这个时间之间才会返回true
#            - Cookie=username,hcxs1986 # 携带cookie，且必须是hcxs1986才会返回true
#            - Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性且这个值为整数的正则表达式
#            - Host=**.year21.top #请求头必须有.year21.top才返回true和路由
#            - Method=GET #请求方式必须为get才返回true和路由
#            - Query=username,\d+ #要有参数名username且值必须为整数才返回true和路由


        - id: payment_route2 # 路由的ID，没有固定规则但要求必须唯一，建议配置服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的动态路由地址
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
            - After=2022-08-09T16:46:43.909+08:00[Asia/Shanghai] #断言，必须在这个时间之后才会返回true

#将网关注册进服务注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://test.dzsc.tk:7007/eureka/
