server:
  port: 80

spring:
  application:
    name: cloud-order-service #设置注册到EurekaServer注册中心使用的名字
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
        #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1

#配置eureka相关信息
eureka:
  client:
    #是否在注册中心注册自己
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true
    #如果是单节点无所谓，但是集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #设置与EurekaServer交互的地址，查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://localhost:7007/eureka #单机eureka版
       defaultZone: http://test.dzsc.tk:7007/eureka/,http://test.dzsc.cf:7008/eureka/ #集群eureka版