server:
  port: 80

#配置eureka相关信息
eureka:
  client:
    #是否在注册中心注册自己
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true
    service-url:
      #设置与EurekaServer交互的地址，查询服务和注册服务都需要依赖这个地址
       defaultZone: http://test.dzsc.tk:7007/eureka/,http://test.dzsc.cf:7008/eureka/ #集群eureka版

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    config.FeignConfig
    top.year21.springcloud.service.PaymentFeignService: debug