#单机eurekaServer配置
#server:
#  port: 7007
#
#eureka:
#  instance:
#    hostname: localhost #eureka服务器端的实例名称
#  client:
#    #是否在注册中心注册自己
#    register-with-eureka: false
#    #false表示自己就是注册中心，职责是维护服务实例，不需要去检索服务
#    fetch-registry: false
#    service-url:
#      #设置与EurekaServer交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/server:

#集群eurekaServer配置
server:
  port: 7007

eureka:
  instance:
    hostname: test.dzsc.tk #eureka服务器端的实例名称
  client:
    #是否在注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，职责是维护服务实例，不需要去检索服务
    fetch-registry: false
    service-url:
      #互相注册，相互守望 即a服务器注册到b服务器中，反之同样
#      defaultZone: http://test.dzsc.cf:7008/eureka/
      defaultZone: http://test.dzsc.tk:7007/eureka/
#  server:
    #关闭自我保护机制，立刻删除不可用的服务
#    enable-self-preservation: false
    #心跳超时时间 2s
#    eviction-interval-timer-in-ms: 2000
