server:
  port: 80

spring:
  application:
    name: consul-consume-order
  cloud:
    consul:
      #consel注册中心地址配置
      host: 192.168.231.134
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true #设置不检测健康状态
